// app/pages/wishlist.vue
<script setup lang="ts">
definePageMeta({ layout: 'default' })
const user = useSupabaseUser()
const supabase = useSupabaseClient()
const favorites = ref<any[]>([])
const loading = ref(true)

onMounted(async () => {
  const { data } = await supabase.from('favorites').select('*, product:products(*, seller:profiles(*))').eq('user_id', user.value?.id)
  favorites.value = data || []
  loading.value = false
})

const remove = async (id: string) => {
  await supabase.from('favorites').delete().eq('id', id)
  favorites.value = favorites.value.filter(f => f.id !== id)
}
</script>

<template>
  <div class="min-h-screen bg-gray-50 dark:bg-gray-900 py-8 px-4">
    <div class="max-w-7xl mx-auto">
      <h1 class="text-3xl font-black mb-8 text-gray-900 dark:text-white">My Wishlist</h1>
      <div v-if="loading" class="grid grid-cols-2 md:grid-cols-4 gap-4">
        <div v-for="i in 4" :key="i" class="skeleton aspect-square rounded-2xl" />
      </div>
      <div v-else-if="favorites.length === 0" class="text-center py-20">
        <div class="text-6xl mb-4">❤️</div>
        <h3 class="text-xl font-bold mb-2">No favorites yet</h3>
        <UButton to="/products" color="primary">Browse Products</UButton>
      </div>
      <div v-else class="grid grid-cols-2 md:grid-cols-4 gap-4">
        <div v-for="fav in favorites" :key="fav.id" class="relative">
          <ProductCard :product="fav.product" />
          <UButton icon="i-lucide-x" color="error" size="xs" class="absolute top-2 right-2 rounded-full" @click="remove(fav.id)" />
        </div>
      </div>
    </div>
  </div>
</template>

// app/wishlist/page.tsx
'use client';

import { useEffect, useState } from 'react';
import { api } from '@/lib/api';
import { Heart, MapPin } from 'lucide-react';

export default function Wishlist() {
  const [products, setProducts] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    loadFavorites();
  }, []);

  const loadFavorites = async () => {
    try {
      const data = await api.getFavorites();
      setProducts(data);
    } catch (error) {
      console.error(error);
    }
    setLoading(false);
  };

  const removeFavorite = async (id: string) => {
    await api.toggleFavorite(id);
    loadFavorites();
  };

  if (loading) return <div className="min-h-screen pt-20 flex items-center justify-center">Loading...</div>;

  return (
    <div className="min-h-screen bg-gray-50 pt-20 pb-12">
      <div className="max-w-7xl mx-auto px-4">
        <h1 className="text-3xl font-bold mb-8">My Wishlist</h1>
        
        {products.length === 0 ? (
          <div className="text-center py-12">
            <Heart className="w-16 h-16 mx-auto text-gray-300 mb-4" />
            <p className="text-gray-600">No items in your wishlist</p>
          </div>
        ) : (
          <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4 md:gap-6">
            {products.map(product => (
              <div key={product._id} className="bg-white rounded-lg shadow overflow-hidden group">
                <div className="relative">
                  <img src={product.images[0]} alt={product.title} className="w-full h-40 md:h-48 object-cover" />
                  <button
                    onClick={() => removeFavorite(product._id)}
                    className="absolute top-2 right-2 p-2 bg-white rounded-full shadow"
                  >
                    <Heart className="w-5 h-5 fill-red-500 text-red-500" />
                  </button>
                </div>
                <div className="p-3 md:p-4">
                  <h3 className="font-semibold text-sm md:text-base mb-2 line-clamp-2">{product.title}</h3>
                  <p className="text-lg md:text-2xl font-bold text-primary-500 mb-2">₦{product.price.toLocaleString()}</p>
                  <div className="flex items-center text-sm text-gray-600 mb-3">
                    <MapPin className="w-4 h-4 mr-1" />
                    {product.location}
                  </div>
                  <a
                    href={`/product/${product._id}`}
                    className="block w-full py-2 bg-primary-500 text-white text-center rounded-lg hover:bg-primary-600"
                  >
                    View Details
                  </a>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}
