// app/admin/page.tsx
"use client";

import { useEffect, useState } from "react";
import { motion } from "framer-motion";
import { Users, Package, ShoppingCart, Wrench, Trash2, CheckCircle, XCircle, Eye } from "lucide-react";
import Navbar from "@/components/Navbar";

const API = 'https://josmkt-com-ng-335845.hostingersite.com/api';

export default function AdminDashboard() {
  const [tab, setTab] = useState<"overview" | "users" | "products" | "providers" | "orders" | "addProduct" | "addProvider">("overview");
  const [stats, setStats] = useState({ users: 0, products: 0, orders: 0, providers: 0 });
  const [users, setUsers] = useState<any[]>([]);
  const [products, setProducts] = useState<any[]>([]);
  const [providers, setProviders] = useState<any[]>([]);
  const [orders, setOrders] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [auth, setAuth] = useState(false);
  const [loginEmail, setLoginEmail] = useState("");
  const [loginPassword, setLoginPassword] = useState("");
  const [loginError, setLoginError] = useState("");

  const [newProduct, setNewProduct] = useState({ title: "", description: "", price: "", category: "", stock: "1" });
  const [newProvider, setNewProvider] = useState({ serviceName: "", category: "", description: "", location: "", phone: "", experience: "", priceRange: "", image: "" });
  const [uploading, setUploading] = useState(false);

  const handleLogin = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoginError("");
    try {
      const res = await fetch(`${API}/auth/login`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ email: loginEmail, password: loginPassword }),
      });
      const data = await res.json();
      if (!res.ok || !data.token) throw new Error(data.message || "Login failed");
      if (data.role !== "admin") throw new Error("Access denied. Admin only.");
      localStorage.setItem("token", data.token);
      localStorage.setItem("admin_auth", "true");
      setAuth(true);
    } catch (err: any) {
      setLoginError(err.message);
    }
  };

  useEffect(() => {
    if (localStorage.getItem("admin_auth") === "true") setAuth(true);
  }, []);

  useEffect(() => {
    if (!auth) return;
    fetchData();
  }, [auth]);

  const fetchData = async () => {
    setLoading(true);
    const token = localStorage.getItem("token");
    const authHeaders = { Authorization: `Bearer ${token}` };
    try {
      const [statsRes, usersRes, productsRes, providersRes, ordersRes] = await Promise.all([
        fetch(`${API}/admin/stats`, { headers: authHeaders }).then(r => r.json()).catch(() => ({ totalUsers: 0, totalProducts: 0, totalOrders: 0 })),
        fetch(`${API}/admin/users`, { headers: authHeaders }).then(r => r.json()).catch(() => []),
        fetch(`${API}/products`).then(r => r.json()).catch(() => []),
        fetch(`${API}/services/all`, { headers: authHeaders }).then(r => r.json()).catch(() => []),
        fetch(`${API}/orders/seller-orders`, { headers: authHeaders }).then(r => r.json()).catch(() => []),
      ]);
      setStats({ users: statsRes.totalUsers || 0, products: statsRes.totalProducts || 0, orders: statsRes.totalOrders || 0, providers: Array.isArray(providersRes) ? providersRes.length : 0 });
      setUsers(Array.isArray(usersRes) ? usersRes : []);
      setProducts(Array.isArray(productsRes) ? productsRes : []);
      setProviders(Array.isArray(providersRes) ? providersRes : []);
      setOrders(Array.isArray(ordersRes) ? ordersRes : []);
    } catch (e) {
      console.error(e);
    }
    setLoading(false);
  };

  const deleteUser = async (id: string) => {
    if (!confirm("Delete this user?")) return;
    const token = localStorage.getItem("token");
    await fetch(`${API}/admin/users/${id}`, { method: "DELETE", headers: { Authorization: `Bearer ${token}` } });
    fetchData();
  };

  const deleteProduct = async (id: string) => {
    if (!confirm("Delete this product?")) return;
    const token = localStorage.getItem("token");
    await fetch(`${API}/products/${id}`, { method: "DELETE", headers: { Authorization: `Bearer ${token}` } });
    fetchData();
  };

  const approveProvider = async (id: string) => {
    const token = localStorage.getItem("token");
    await fetch(`${API}/services/${id}/status`, { method: "PATCH", headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}` }, body: JSON.stringify({ status: "approved" }) });
    fetchData();
  };

  const deleteProvider = async (id: string) => {
    if (!confirm("Delete this provider?")) return;
    const token = localStorage.getItem("token");
    await fetch(`${API}/services/${id}`, { method: "DELETE", headers: { Authorization: `Bearer ${token}` } });
    fetchData();
  };

  const addProduct = async (e: React.FormEvent) => {
    e.preventDefault();
    const token = localStorage.getItem("token");
    const res = await fetch(`${API}/products/draft`, {
      method: "POST",
      headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}` },
      body: JSON.stringify({ ...newProduct, price: parseFloat(newProduct.price), stock: parseInt(newProduct.stock), images: [] }),
    });
    if (res.ok) {
      setNewProduct({ title: "", description: "", price: "", category: "", stock: "1" });
      setTab("products");
      fetchData();
    } else {
      const data = await res.json();
      alert(data.message || "Failed to add product");
    }
  };

  const handleImageUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;
    setUploading(true);
    const formData = new FormData();
    formData.append("images", file);
    try {
      const token = localStorage.getItem("token");
      const res = await fetch(`${API}/products`, { method: "POST", headers: { Authorization: `Bearer ${token}` }, body: formData });
      const data = await res.json();
      if (data.images?.[0]) setNewProvider({ ...newProvider, image: data.images[0] });
    } catch (err) {
      alert("Upload failed");
    }
    setUploading(false);
  };

  const addProvider = async (e: React.FormEvent) => {
    e.preventDefault();
    const token = localStorage.getItem("token");
    if (!token) { alert("Not logged in. Please login again."); return; }
    try {
      const res = await fetch(`${API}/services/apply`, {
        method: "POST",
        headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}` },
        body: JSON.stringify(newProvider),
      });
      const data = await res.json();
      if (data._id) {
        alert("Provider added successfully!");
        setNewProvider({ serviceName: "", category: "", description: "", location: "", phone: "", experience: "", priceRange: "", image: "" });
        setTab("providers");
        fetchData();
      } else {
        alert("Error: " + (data.message || JSON.stringify(data)));
      }
    } catch (err: any) {
      alert("Network error: " + err.message);
    }
  };

  if (!auth) {
    return (
      <>
        <Navbar />
        <div className="min-h-screen flex items-center justify-center bg-gray-50 dark:bg-gray-900 px-4">
          <form onSubmit={handleLogin} className="bg-white dark:bg-gray-800 p-8 rounded-2xl shadow-xl max-w-sm w-full">
            <h1 className="text-2xl font-bold mb-6 text-center">Admin Access</h1>
            {loginError && <p className="text-red-500 text-sm mb-4 text-center">{loginError}</p>}
            <input
              type="email"
              value={loginEmail}
              onChange={(e) => setLoginEmail(e.target.value)}
              placeholder="Admin email"
              className="w-full px-4 py-3 border-2 rounded-xl mb-4 focus:border-emerald-500 focus:outline-none dark:bg-gray-700 dark:border-gray-600 dark:text-white"
            />
            <input
              type="password"
              value={loginPassword}
              onChange={(e) => setLoginPassword(e.target.value)}
              placeholder="Password"
              className="w-full px-4 py-3 border-2 rounded-xl mb-4 focus:border-emerald-500 focus:outline-none dark:bg-gray-700 dark:border-gray-600 dark:text-white"
            />
            <button type="submit" className="w-full py-3 bg-emerald-500 text-white rounded-xl font-bold hover:bg-emerald-600">
              Login
            </button>
          </form>
        </div>
      </>
    );
  }

  return (
    <>
      <Navbar />
      <div className="min-h-screen bg-gray-50 dark:bg-gray-900 py-8 px-4">
        <div className="max-w-7xl mx-auto">
          <div className="flex items-center justify-between mb-8">
            <h1 className="text-3xl font-bold text-gray-900 dark:text-white">Admin Dashboard</h1>
            <button onClick={() => { localStorage.removeItem("admin_auth"); localStorage.removeItem("token"); setAuth(false); }} className="text-sm text-red-500 hover:underline">
              Logout
            </button>
          </div>

          {/* Stats */}
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-8">
            {[
              { label: "Users", value: stats.users, icon: Users, color: "from-blue-500 to-indigo-500" },
              { label: "Products", value: stats.products, icon: Package, color: "from-emerald-500 to-teal-500" },
              { label: "Orders", value: stats.orders, icon: ShoppingCart, color: "from-amber-500 to-orange-500" },
              { label: "Providers", value: stats.providers, icon: Wrench, color: "from-purple-500 to-pink-500" },
            ].map((stat) => (
              <motion.div
                key={stat.label}
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                className="bg-white dark:bg-gray-800 rounded-2xl p-5 shadow-sm"
              >
                <div className={`w-10 h-10 rounded-xl bg-gradient-to-br ${stat.color} flex items-center justify-center mb-3`}>
                  <stat.icon className="w-5 h-5 text-white" />
                </div>
                <p className="text-2xl font-bold text-gray-900 dark:text-white">{stat.value}</p>
                <p className="text-sm text-gray-500">{stat.label}</p>
              </motion.div>
            ))}
          </div>

          <div className="flex gap-2 mb-6 overflow-x-auto">
            {(["overview", "users", "products", "addProduct", "providers", "addProvider", "orders"] as const).map((t) => (
              <button
                key={t}
                onClick={() => setTab(t)}
                className={`px-4 py-2 rounded-xl text-sm font-medium whitespace-nowrap transition-all ${
                  tab === t ? "bg-emerald-500 text-white" : "bg-white dark:bg-gray-800 text-gray-600 dark:text-gray-300"
                }`}
              >
                {t === "addProduct" ? "+ Product" : t === "addProvider" ? "+ Provider" : t.charAt(0).toUpperCase() + t.slice(1)}
              </button>
            ))}
          </div>

          {loading ? (
            <div className="text-center py-20 text-gray-500">Loading...</div>
          ) : (
            <>
              {/* Users Tab */}
              {tab === "users" && (
                <div className="bg-white dark:bg-gray-800 rounded-2xl shadow-sm overflow-hidden">
                  <div className="overflow-x-auto">
                    <table className="w-full text-sm">
                      <thead className="bg-gray-50 dark:bg-gray-700">
                        <tr>
                          <th className="px-4 py-3 text-left font-semibold">Name</th>
                          <th className="px-4 py-3 text-left font-semibold">Email</th>
                          <th className="px-4 py-3 text-left font-semibold">Role</th>
                          <th className="px-4 py-3 text-left font-semibold">Verified</th>
                          <th className="px-4 py-3 text-left font-semibold">Actions</th>
                        </tr>
                      </thead>
                      <tbody className="divide-y dark:divide-gray-700">
                        {users.map((user) => (
                          <tr key={user.id} className="hover:bg-gray-50 dark:hover:bg-gray-700/50">
                            <td className="px-4 py-3 font-medium">{user.name}</td>
                            <td className="px-4 py-3 text-gray-500">{user.email}</td>
                            <td className="px-4 py-3">
                              <span className={`px-2 py-1 rounded-full text-xs font-medium ${user.role === 'admin' ? 'bg-purple-100 text-purple-700' : user.role === 'seller' ? 'bg-emerald-100 text-emerald-700' : 'bg-gray-100 text-gray-700'}`}>
                                {user.role}
                              </span>
                            </td>
                            <td className="px-4 py-3">
                              {user.verified ? <CheckCircle className="w-4 h-4 text-emerald-500" /> : <XCircle className="w-4 h-4 text-red-400" />}
                            </td>
                            <td className="px-4 py-3">
                              <button onClick={() => deleteUser(user.id)} className="text-red-500 hover:text-red-700">
                                <Trash2 className="w-4 h-4" />
                              </button>
                            </td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
                  {users.length === 0 && <p className="text-center py-8 text-gray-500">No users yet</p>}
                </div>
              )}

              {/* Products Tab */}
              {tab === "products" && (
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                  {products.map((product) => (
                    <div key={product.id} className="bg-white dark:bg-gray-800 rounded-2xl p-5 shadow-sm">
                      <div className="flex justify-between items-start mb-3">
                        <h3 className="font-bold text-gray-900 dark:text-white">{product.title}</h3>
                        <button onClick={() => deleteProduct(product.id)} className="text-red-500 hover:text-red-700">
                          <Trash2 className="w-4 h-4" />
                        </button>
                      </div>
                      <p className="text-sm text-gray-500 mb-2">{product.description}</p>
                      <div className="flex justify-between items-center">
                        <span className="font-bold text-emerald-600">₦{product.price?.toLocaleString()}</span>
                        <span className="text-xs bg-gray-100 dark:bg-gray-700 px-2 py-1 rounded-full">{product.category}</span>
                      </div>
                      <div className="flex items-center gap-2 mt-2 text-xs text-gray-400">
                        <Eye className="w-3 h-3" /> {product.views || 0} views
                        <span>• Stock: {product.stock}</span>
                      </div>
                    </div>
                  ))}
                  {products.length === 0 && <p className="col-span-full text-center py-8 text-gray-500">No products yet</p>}
                </div>
              )}

              {/* Providers Tab */}
              {tab === "providers" && (
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  {providers.map((provider) => (
                    <div key={provider._id} className="bg-white dark:bg-gray-800 rounded-2xl p-5 shadow-sm">
                      <div className="flex justify-between items-start mb-3">
                        <div>
                          <h3 className="font-bold text-gray-900 dark:text-white">{provider.serviceName}</h3>
                          <p className="text-sm text-gray-500">{provider.category} • {provider.location}</p>
                        </div>
                        <div className="flex items-center gap-2">
                          {provider.status === "approved" ? (
                            <span className="px-2 py-1 bg-emerald-100 text-emerald-700 text-xs rounded-full font-medium">Approved</span>
                          ) : (
                            <button onClick={() => approveProvider(provider._id)} className="px-3 py-1 bg-emerald-500 text-white text-xs rounded-full font-medium hover:bg-emerald-600">
                              Approve
                            </button>
                          )}
                          <button onClick={() => deleteProvider(provider._id)} className="text-red-500 hover:text-red-700">
                            <Trash2 className="w-4 h-4" />
                          </button>
                        </div>
                      </div>
                      <p className="text-sm text-gray-500">{provider.description}</p>
                      <p className="text-sm text-gray-400 mt-2">📞 {provider.phone}</p>
                      {provider.experience && <p className="text-sm text-gray-400">🕐 {provider.experience}</p>}
                      {provider.priceRange && <p className="text-sm text-gray-400">💰 {provider.priceRange}</p>}
                    </div>
                  ))}
                  {providers.length === 0 && <p className="col-span-full text-center py-8 text-gray-500">No service providers yet</p>}
                </div>
              )}

              {/* Orders Tab */}
              {tab === "orders" && (
                <div className="bg-white dark:bg-gray-800 rounded-2xl shadow-sm overflow-hidden">
                  <div className="overflow-x-auto">
                    <table className="w-full text-sm">
                      <thead className="bg-gray-50 dark:bg-gray-700">
                        <tr>
                          <th className="px-4 py-3 text-left font-semibold">Order ID</th>
                          <th className="px-4 py-3 text-left font-semibold">Product</th>
                          <th className="px-4 py-3 text-left font-semibold">Total</th>
                          <th className="px-4 py-3 text-left font-semibold">Status</th>
                          <th className="px-4 py-3 text-left font-semibold">Date</th>
                        </tr>
                      </thead>
                      <tbody className="divide-y dark:divide-gray-700">
                        {orders.map((order) => (
                          <tr key={order.id} className="hover:bg-gray-50 dark:hover:bg-gray-700/50">
                            <td className="px-4 py-3 font-mono text-xs">{order.id?.slice(0, 8)}...</td>
                            <td className="px-4 py-3">{order.product?.title || "—"}</td>
                            <td className="px-4 py-3 font-bold">₦{order.total?.toLocaleString()}</td>
                            <td className="px-4 py-3">
                              <span className={`px-2 py-1 rounded-full text-xs font-medium ${
                                order.status === 'delivered' ? 'bg-emerald-100 text-emerald-700' :
                                order.status === 'pending' ? 'bg-amber-100 text-amber-700' :
                                'bg-blue-100 text-blue-700'
                              }`}>
                                {order.status}
                              </span>
                            </td>
                            <td className="px-4 py-3 text-gray-500">{new Date(order.createdAt).toLocaleDateString()}</td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
                  {orders.length === 0 && <p className="text-center py-8 text-gray-500">No orders yet</p>}
                </div>
              )}

              {/* Overview Tab */}
              {tab === "overview" && (
                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                  <div className="bg-white dark:bg-gray-800 rounded-2xl p-6 shadow-sm">
                    <h3 className="font-bold text-lg mb-4">Recent Users</h3>
                    {users.slice(0, 5).map((user) => (
                      <div key={user.id} className="flex items-center justify-between py-2 border-b dark:border-gray-700 last:border-0">
                        <div>
                          <p className="font-medium text-sm">{user.name}</p>
                          <p className="text-xs text-gray-500">{user.email}</p>
                        </div>
                        <span className="text-xs bg-gray-100 dark:bg-gray-700 px-2 py-1 rounded-full">{user.role}</span>
                      </div>
                    ))}
                    {users.length === 0 && <p className="text-gray-500 text-sm">No users yet</p>}
                  </div>
                  <div className="bg-white dark:bg-gray-800 rounded-2xl p-6 shadow-sm">
                    <h3 className="font-bold text-lg mb-4">Recent Products</h3>
                    {products.slice(0, 5).map((product) => (
                      <div key={product.id} className="flex items-center justify-between py-2 border-b dark:border-gray-700 last:border-0">
                        <div>
                          <p className="font-medium text-sm">{product.title}</p>
                          <p className="text-xs text-gray-500">{product.category}</p>
                        </div>
                        <span className="font-bold text-sm text-emerald-600">₦{product.price?.toLocaleString()}</span>
                      </div>
                    ))}
                    {products.length === 0 && <p className="text-gray-500 text-sm">No products yet</p>}
                  </div>
                </div>
              )}

              {/* Add Product Tab */}
              {tab === "addProduct" && (
                <div className="bg-white dark:bg-gray-800 rounded-2xl p-6 shadow-sm max-w-2xl">
                  <h3 className="font-bold text-lg mb-6">Add New Product</h3>
                  <form onSubmit={addProduct} className="space-y-4">
                    <input type="text" required placeholder="Product title" value={newProduct.title} onChange={(e) => setNewProduct({ ...newProduct, title: e.target.value })} className="w-full px-4 py-3 border-2 rounded-xl focus:border-emerald-500 focus:outline-none dark:bg-gray-700 dark:border-gray-600 dark:text-white" />
                    <textarea required placeholder="Description" value={newProduct.description} onChange={(e) => setNewProduct({ ...newProduct, description: e.target.value })} className="w-full px-4 py-3 border-2 rounded-xl focus:border-emerald-500 focus:outline-none dark:bg-gray-700 dark:border-gray-600 dark:text-white" rows={3} />
                    <div className="grid grid-cols-2 gap-4">
                      <input type="number" required placeholder="Price (₦)" value={newProduct.price} onChange={(e) => setNewProduct({ ...newProduct, price: e.target.value })} className="w-full px-4 py-3 border-2 rounded-xl focus:border-emerald-500 focus:outline-none dark:bg-gray-700 dark:border-gray-600 dark:text-white" />
                      <input type="number" required placeholder="Stock" value={newProduct.stock} onChange={(e) => setNewProduct({ ...newProduct, stock: e.target.value })} className="w-full px-4 py-3 border-2 rounded-xl focus:border-emerald-500 focus:outline-none dark:bg-gray-700 dark:border-gray-600 dark:text-white" />
                    </div>
                    <select required value={newProduct.category} onChange={(e) => setNewProduct({ ...newProduct, category: e.target.value })} className="w-full px-4 py-3 border-2 rounded-xl focus:border-emerald-500 focus:outline-none dark:bg-gray-700 dark:border-gray-600 dark:text-white">
                      <option value="">Select category</option>
                      <option value="phones">Phones</option>
                      <option value="gadgets">Gadgets</option>
                      <option value="electronics">Electronics</option>
                      <option value="fashion">Fashion</option>
                      <option value="food">Food</option>
                      <option value="furniture">Furniture</option>
                    </select>
                    <button type="submit" className="w-full py-3 bg-emerald-500 text-white rounded-xl font-bold hover:bg-emerald-600">Add Product</button>
                  </form>
                </div>
              )}

              {/* Add Provider Tab */}
              {tab === "addProvider" && (
                <div className="bg-white dark:bg-gray-800 rounded-2xl p-6 shadow-sm max-w-2xl">
                  <h3 className="font-bold text-lg mb-6">Add Service Provider</h3>
                  <form onSubmit={addProvider} className="space-y-4">
                    <input type="text" required placeholder="Service/Business name" value={newProvider.serviceName} onChange={(e) => setNewProvider({ ...newProvider, serviceName: e.target.value })} className="w-full px-4 py-3 border-2 rounded-xl focus:border-emerald-500 focus:outline-none dark:bg-gray-700 dark:border-gray-600 dark:text-white" />
                    <textarea required placeholder="Description" value={newProvider.description} onChange={(e) => setNewProvider({ ...newProvider, description: e.target.value })} className="w-full px-4 py-3 border-2 rounded-xl focus:border-emerald-500 focus:outline-none dark:bg-gray-700 dark:border-gray-600 dark:text-white" rows={3} />
                    <div className="grid grid-cols-2 gap-4">
                      <input type="tel" required placeholder="Phone number" value={newProvider.phone} onChange={(e) => setNewProvider({ ...newProvider, phone: e.target.value })} className="w-full px-4 py-3 border-2 rounded-xl focus:border-emerald-500 focus:outline-none dark:bg-gray-700 dark:border-gray-600 dark:text-white" />
                      <input type="text" placeholder="Location" value={newProvider.location} onChange={(e) => setNewProvider({ ...newProvider, location: e.target.value })} className="w-full px-4 py-3 border-2 rounded-xl focus:border-emerald-500 focus:outline-none dark:bg-gray-700 dark:border-gray-600 dark:text-white" />
                    </div>
                    <div className="grid grid-cols-2 gap-4">
                      <input type="text" placeholder="Experience (e.g. 5 years)" value={newProvider.experience} onChange={(e) => setNewProvider({ ...newProvider, experience: e.target.value })} className="w-full px-4 py-3 border-2 rounded-xl focus:border-emerald-500 focus:outline-none dark:bg-gray-700 dark:border-gray-600 dark:text-white" />
                      <input type="text" placeholder="Price range (e.g. ₦5,000 - ₦50,000)" value={newProvider.priceRange} onChange={(e) => setNewProvider({ ...newProvider, priceRange: e.target.value })} className="w-full px-4 py-3 border-2 rounded-xl focus:border-emerald-500 focus:outline-none dark:bg-gray-700 dark:border-gray-600 dark:text-white" />
                    </div>
                    <select required value={newProvider.category} onChange={(e) => setNewProvider({ ...newProvider, category: e.target.value })} className="w-full px-4 py-3 border-2 rounded-xl focus:border-emerald-500 focus:outline-none dark:bg-gray-700 dark:border-gray-600 dark:text-white">
                      <option value="">Select category</option>
                      <option value="plumbing">Plumbing</option>
                      <option value="electrical">Electricians</option>
                      <option value="ac">AC Installation</option>
                      <option value="baking">Bakers & Catering</option>
                      <option value="painting">Painting</option>
                      <option value="mechanic">Auto Mechanic</option>
                      <option value="barbing">Barbing & Salon</option>
                      <option value="carpentry">Carpentry</option>
                      <option value="tailoring">Tailoring</option>
                      <option value="photography">Photography</option>
                      <option value="tech">Tech & Repairs</option>
                      <option value="logistics">Logistics & Moving</option>
                      <option value="cleaning">Cleaning</option>
                      <option value="childcare">Childcare</option>
                      <option value="pets">Pets</option>
                      <option value="fitness">Fitness</option>
                    </select>
                    <div>
                      <label className="text-sm font-semibold text-gray-700 dark:text-gray-300 mb-2 block">Business Photo</label>
                      <input type="file" accept="image/*" onChange={handleImageUpload} className="w-full px-4 py-3 border-2 rounded-xl focus:border-emerald-500 focus:outline-none dark:bg-gray-700 dark:border-gray-600 dark:text-white" />
                      {uploading && <p className="text-sm text-emerald-500 mt-1">Uploading...</p>}
                      {newProvider.image && <img src={newProvider.image} alt="Preview" className="mt-2 w-32 h-32 object-cover rounded-xl" />}
                    </div>
                    <button type="submit" className="w-full py-3 bg-emerald-500 text-white rounded-xl font-bold hover:bg-emerald-600">Add Provider</button>
                  </form>
                </div>
              )}
            </>
          )}
        </div>
      </div>
    </>
  );
}

// app/pages/admin.vue
<script setup lang="ts">
definePageMeta({ middleware: 'auth' })
const user = useSupabaseUser()
const supabase = useSupabaseClient()
const toast = useToast()
const tab = ref('overview')
const loading = ref(true)

const stats = ref({ users: 0, products: 0, orders: 0, revenue: 0 })
const users = ref<any[]>([])
const products = ref<any[]>([])
const orders = ref<any[]>([])

// Guard: only allow admin
const isAdmin = computed(() => user.value?.email === 'kararzoe@gmail.com' || user.value?.user_metadata?.role === 'admin')

onMounted(async () => {
  if (!isAdmin.value) return navigateTo('/dashboard')

  const [{ data: u }, { data: p }, { data: o }] = await Promise.all([
    supabase.from('profiles').select('*').order('created_at', { ascending: false }),
    supabase.from('products').select('*, seller:profiles(full_name)').order('created_at', { ascending: false }),
    supabase.from('orders').select('*, product:products(title, price), buyer:profiles(full_name)').order('created_at', { ascending: false })
  ])
  users.value = u || []
  products.value = p || []
  orders.value = o || []
  stats.value = {
    users: users.value.length,
    products: products.value.length,
    orders: orders.value.length,
    revenue: orders.value.filter(o => o.status === 'completed').reduce((s, o) => s + (o.product?.price || 0), 0)
  }
  loading.value = false
})

const deleteProduct = async (id: string) => {
  await supabase.from('products').delete().eq('id', id)
  products.value = products.value.filter(p => p.id !== id)
  stats.value.products--
  toast.add({ title: 'Product deleted', color: 'success' })
}

const updateOrderStatus = async (id: string, status: string) => {
  await supabase.from('orders').update({ status }).eq('id', id)
  const o = orders.value.find(o => o.id === id)
  if (o) o.status = status
  toast.add({ title: 'Order updated', color: 'success' })
}

// Service providers from Render backend
const serviceProviders = ref<any[]>([])
const loadingServices = ref(false)

const loadServiceProviders = async () => {
  loadingServices.value = true
  try {
    const data = await $fetch<any[]>('https://jos-backend.onrender.com/api/services/all', {
      headers: { Authorization: `Bearer ${(await supabase.auth.getSession()).data.session?.access_token}` }
    })
    serviceProviders.value = Array.isArray(data) ? data : []
  } catch {
    // fallback - try without auth since admin is checking
    serviceProviders.value = []
  }
  loadingServices.value = false
}

const updateServiceStatus = async (id: string, status: string) => {
  try {
    await $fetch(`https://jos-backend.onrender.com/api/services/${id}/status`, {
      method: 'PATCH',
      body: { status }
    })
    const s = serviceProviders.value.find(s => s._id === id)
    if (s) s.status = status
    toast.add({ title: `Provider ${status}`, color: 'success' })
  } catch {
    toast.add({ title: 'Failed to update', color: 'error' })
  }
}

const deleteServiceProvider = async (id: string) => {
  try {
    await $fetch(`https://jos-backend.onrender.com/api/services/${id}`, { method: 'DELETE' })
    serviceProviders.value = serviceProviders.value.filter(s => s._id !== id)
    toast.add({ title: 'Provider deleted', color: 'success' })
  } catch {
    toast.add({ title: 'Failed to delete', color: 'error' })
  }
}

watch(tab, (val) => { if (val === 'services') loadServiceProviders() })

const tabs = [
  { label: 'Overview', value: 'overview', icon: 'i-lucide-layout-dashboard' },
  { label: 'Users', value: 'users', icon: 'i-lucide-users' },
  { label: 'Products', value: 'products', icon: 'i-lucide-package' },
  { label: 'Orders', value: 'orders', icon: 'i-lucide-shopping-bag' },
  { label: 'Service Providers', value: 'services', icon: 'i-lucide-wrench' },
  { label: '+ Add Provider', value: 'addProvider', icon: 'i-lucide-plus-circle' },
]

const CLOUDINARY = 'https://api.cloudinary.com/v1_1/dfye3j2bs/image/upload'
const newProvider = reactive({ serviceName: '', category: '', description: '', phone: '', location: '', experience: '', priceRange: '', image: '', gallery: [] as string[] })
const uploading = ref(false)

const uploadImage = async (file: File): Promise<string> => {
  const fd = new FormData()
  fd.append('file', file)
  fd.append('upload_preset', 'jos_marketplace')
  const res = await fetch(CLOUDINARY, { method: 'POST', body: fd })
  const data = await res.json()
  return data.secure_url || ''
}

const handleLogoUpload = async (e: Event) => {
  const file = (e.target as HTMLInputElement).files?.[0]
  if (!file) return
  uploading.value = true
  newProvider.image = await uploadImage(file)
  uploading.value = false
}

const handleGalleryUpload = async (e: Event) => {
  const files = (e.target as HTMLInputElement).files
  if (!files) return
  uploading.value = true
  for (const file of Array.from(files)) {
    const url = await uploadImage(file)
    if (url) newProvider.gallery.push(url)
  }
  uploading.value = false
}

const submitProvider = async () => {
  try {
    const data = await $fetch<any>('https://jos-backend.onrender.com/api/services/apply-public', {
      method: 'POST',
      body: newProvider
    })
    if (data._id || data.success) {
      toast.add({ title: 'Provider added!', color: 'success' })
      Object.assign(newProvider, { serviceName: '', category: '', description: '', phone: '', location: '', experience: '', priceRange: '', image: '', gallery: [] })
      tab.value = 'services'
      loadServiceProviders()
    } else {
      toast.add({ title: data.message || 'Failed', color: 'error' })
    }
  } catch {
    toast.add({ title: 'Network error', color: 'error' })
  }
}

const serviceCategories = ['plumbing','electrical','ac','furniture','catering','painting','mechanic','barbing','carpentry','fashion-design','shoemaking','photography','tech','logistics','laundry','education','perfumery','makeup','event-planning','rentals','mason','phone-accessories','legal','housing-agent','e-wallet']

const statCards = computed(() => [
  { label: 'Total Users', value: stats.value.users, icon: 'i-lucide-users', color: 'bg-blue-500' },
  { label: 'Total Products', value: stats.value.products, icon: 'i-lucide-package', color: 'bg-purple-500' },
  { label: 'Total Orders', value: stats.value.orders, icon: 'i-lucide-shopping-bag', color: 'bg-orange-500' },
  { label: 'Revenue', value: `₦${stats.value.revenue.toLocaleString()}`, icon: 'i-lucide-trending-up', color: 'bg-green-500' },
])
</script>

<template>
  <div class="min-h-screen bg-gray-50 dark:bg-gray-900 py-8 px-4">
    <div class="max-w-7xl mx-auto">
      <div class="flex items-center justify-between mb-8">
        <div class="flex items-center gap-3">
          <UButton to="/dashboard" icon="i-lucide-arrow-left" variant="ghost" color="neutral" />
          <div>
            <h1 class="text-3xl font-black text-gray-900 dark:text-white">Admin Dashboard</h1>
            <p class="text-sm text-gray-500">Jos Marketplace Control Panel</p>
          </div>
        </div>
        <UBadge color="error" size="lg" icon="i-lucide-shield">Admin</UBadge>
      </div>

      <!-- Stats -->
      <div class="grid grid-cols-2 md:grid-cols-4 gap-4 mb-8">
        <div v-for="s in statCards" :key="s.label" class="bg-white dark:bg-gray-800 rounded-2xl p-4 md:p-6 shadow-md card-hover">
          <div class="w-10 h-10 rounded-xl flex items-center justify-center mb-3" :class="s.color">
            <UIcon :name="s.icon" class="w-5 h-5 text-white" />
          </div>
          <p class="text-2xl font-black">{{ s.value }}</p>
          <p class="text-xs text-gray-500">{{ s.label }}</p>
        </div>
      </div>

      <!-- Tabs -->
      <div class="flex gap-2 mb-6 flex-wrap">
        <UButton v-for="t in tabs" :key="t.value" :icon="t.icon" :variant="tab === t.value ? 'solid' : 'outline'" :color="tab === t.value ? 'primary' : 'neutral'" size="sm" @click="tab = t.value">
          {{ t.label }}
        </UButton>
      </div>

      <div v-if="loading" class="space-y-3">
        <div v-for="i in 5" :key="i" class="skeleton h-16 rounded-xl" />
      </div>

      <!-- Overview -->
      <div v-else-if="tab === 'overview'" class="grid md:grid-cols-2 gap-6">
        <div class="bg-white dark:bg-gray-800 rounded-2xl p-6 shadow-md">
          <h3 class="font-black text-lg mb-4">Recent Users</h3>
          <div class="space-y-3">
            <div v-for="u in users.slice(0, 5)" :key="u.id" class="flex items-center gap-3">
              <div class="w-9 h-9 rounded-full bg-primary-100 dark:bg-primary-900/30 flex items-center justify-center overflow-hidden">
                <img v-if="u.avatar_url" :src="u.avatar_url" class="w-full h-full object-cover" />
                <UIcon v-else name="i-lucide-user" class="w-4 h-4 text-primary-600" />
              </div>
              <div class="flex-1 min-w-0">
                <p class="font-semibold text-sm truncate">{{ u.full_name || 'No name' }}</p>
                <p class="text-xs text-gray-400 truncate">{{ u.id }}</p>
              </div>
              <p class="text-xs text-gray-400">{{ new Date(u.created_at).toLocaleDateString() }}</p>
            </div>
          </div>
        </div>
        <div class="bg-white dark:bg-gray-800 rounded-2xl p-6 shadow-md">
          <h3 class="font-black text-lg mb-4">Recent Products</h3>
          <div class="space-y-3">
            <div v-for="p in products.slice(0, 5)" :key="p.id" class="flex items-center gap-3">
              <div class="w-9 h-9 rounded-lg bg-gray-100 dark:bg-gray-700 overflow-hidden flex-shrink-0">
                <img v-if="p.images?.[0]" :src="p.images[0]" class="w-full h-full object-cover" />
                <div v-else class="w-full h-full flex items-center justify-center text-lg">📦</div>
              </div>
              <div class="flex-1 min-w-0">
                <p class="font-semibold text-sm truncate">{{ p.title }}</p>
                <p class="text-xs text-primary-600 font-bold">₦{{ p.price?.toLocaleString() }}</p>
              </div>
              <UButton icon="i-lucide-trash" variant="ghost" color="error" size="xs" @click="deleteProduct(p.id)" />
            </div>
          </div>
        </div>
      </div>

      <!-- Users Tab -->
      <div v-else-if="tab === 'users'" class="space-y-3">
        <div v-for="u in users" :key="u.id" class="bg-white dark:bg-gray-800 rounded-xl p-4 shadow-sm flex items-center gap-4">
          <div class="w-10 h-10 rounded-full bg-primary-100 dark:bg-primary-900/30 flex items-center justify-center overflow-hidden flex-shrink-0">
            <img v-if="u.avatar_url" :src="u.avatar_url" class="w-full h-full object-cover" />
            <UIcon v-else name="i-lucide-user" class="w-5 h-5 text-primary-600" />
          </div>
          <div class="flex-1 min-w-0">
            <p class="font-bold truncate">{{ u.full_name || 'No name' }}</p>
            <p class="text-sm text-gray-500 truncate">{{ u.phone || 'No phone' }}</p>
          </div>
          <p class="text-xs text-gray-400 hidden md:block">{{ new Date(u.created_at).toLocaleDateString() }}</p>
          <NuxtLink :to="`/seller/${u.id}`">
            <UButton icon="i-lucide-eye" variant="ghost" size="xs" />
          </NuxtLink>
        </div>
      </div>

      <!-- Products Tab -->
      <div v-else-if="tab === 'products'" class="space-y-3">
        <div v-for="p in products" :key="p.id" class="bg-white dark:bg-gray-800 rounded-xl p-4 shadow-sm flex items-center gap-4">
          <div class="w-14 h-14 rounded-lg bg-gray-100 dark:bg-gray-700 overflow-hidden flex-shrink-0">
            <img v-if="p.images?.[0]" :src="p.images[0]" :alt="p.title" class="w-full h-full object-cover" />
            <div v-else class="w-full h-full flex items-center justify-center text-2xl">📦</div>
          </div>
          <div class="flex-1 min-w-0">
            <p class="font-bold truncate">{{ p.title }}</p>
            <p class="text-sm text-primary-600 font-semibold">₦{{ p.price?.toLocaleString() }}</p>
            <p class="text-xs text-gray-400">by {{ p.seller?.full_name || 'Unknown' }}</p>
          </div>
          <div class="flex gap-2">
            <NuxtLink :to="`/product/${p.id}`">
              <UButton icon="i-lucide-eye" variant="ghost" size="xs" />
            </NuxtLink>
            <UButton icon="i-lucide-trash" variant="ghost" color="error" size="xs" @click="deleteProduct(p.id)" />
          </div>
        </div>
      </div>

      <!-- Service Providers Tab -->
      <div v-else-if="tab === 'services'">
        <div class="flex justify-between items-center mb-4">
          <p class="text-sm text-gray-500">All service provider applications from the backend</p>
          <UButton icon="i-lucide-refresh-cw" size="xs" variant="outline" @click="loadServiceProviders">Refresh</UButton>
        </div>
        <div v-if="loadingServices" class="space-y-3">
          <div v-for="i in 4" :key="i" class="skeleton h-20 rounded-xl" />
        </div>
        <div v-else-if="serviceProviders.length === 0" class="text-center py-12 text-gray-500">
          <p>No service providers found</p>
          <p class="text-xs mt-1">Make sure the Render backend is running</p>
        </div>
        <div v-else class="space-y-3">
          <div v-for="s in serviceProviders" :key="s._id" class="bg-white dark:bg-gray-800 rounded-xl p-4 shadow-sm flex items-center gap-4">
            <div class="w-12 h-12 rounded-full overflow-hidden bg-emerald-100 flex-shrink-0 flex items-center justify-center">
              <img v-if="s.image" :src="s.image" class="w-full h-full object-cover" />
              <span v-else class="text-emerald-600 font-bold">{{ s.serviceName?.charAt(0) }}</span>
            </div>
            <div class="flex-1 min-w-0">
              <p class="font-bold truncate">{{ s.serviceName }}</p>
              <p class="text-sm text-gray-500">{{ s.category }} · {{ s.location }}</p>
              <p class="text-xs text-gray-400">{{ s.phone }}</p>
            </div>
            <UBadge :color="s.status === 'approved' ? 'success' : s.status === 'rejected' ? 'error' : 'warning'" size="sm">{{ s.status }}</UBadge>
            <div class="flex gap-1">
              <UButton v-if="s.status !== 'approved'" size="xs" color="success" @click="updateServiceStatus(s._id, 'approved')">Approve</UButton>
              <UButton v-if="s.status !== 'rejected'" size="xs" color="warning" variant="outline" @click="updateServiceStatus(s._id, 'rejected')">Reject</UButton>
              <UButton size="xs" color="error" variant="ghost" icon="i-lucide-trash" @click="deleteServiceProvider(s._id)" />
            </div>
          </div>
        </div>
      </div>

      <!-- Orders Tab -->
      <div v-else-if="tab === 'orders'" class="space-y-3">
        <div v-for="o in orders" :key="o.id" class="bg-white dark:bg-gray-800 rounded-xl p-4 shadow-sm flex items-center gap-4">
          <div class="text-3xl">📦</div>
          <div class="flex-1 min-w-0">
            <p class="font-bold truncate">{{ o.product?.title }}</p>
            <p class="text-sm text-gray-500">{{ o.buyer?.full_name || 'Unknown buyer' }}</p>
            <p class="text-xs text-gray-400">{{ new Date(o.created_at).toLocaleDateString() }}</p>
          </div>
          <p class="font-black text-primary-600 hidden md:block">₦{{ o.product?.price?.toLocaleString() }}</p>
          <USelect
            :model-value="o.status"
            :items="['pending', 'processing', 'completed', 'cancelled']"
            size="xs"
            class="w-32"
            @update:model-value="updateOrderStatus(o.id, $event)"
          />
        </div>
      </div>
      <!-- Add Provider Tab -->
      <div v-else-if="tab === 'addProvider'" class="bg-white dark:bg-gray-800 rounded-2xl p-6 shadow-md max-w-2xl">
        <h3 class="font-black text-xl mb-6">Add Service Provider</h3>
        <form class="space-y-4" @submit.prevent="submitProvider">
          <UInput v-model="newProvider.serviceName" required placeholder="Business / Service name" size="lg" />
          <UTextarea v-model="newProvider.description" required placeholder="Description" :rows="3" />
          <div class="grid grid-cols-2 gap-4">
            <UInput v-model="newProvider.phone" required placeholder="Phone number" />
            <UInput v-model="newProvider.location" placeholder="Location (e.g. Terminus, Jos)" />
          </div>
          <div class="grid grid-cols-2 gap-4">
            <UInput v-model="newProvider.experience" placeholder="Experience (e.g. 5 years)" />
            <UInput v-model="newProvider.priceRange" placeholder="Price range (e.g. ₦5k - ₦50k)" />
          </div>
          <USelect
            v-model="newProvider.category"
            :items="serviceCategories.map(c => ({ label: c.replace(/-/g,'  ').replace(/\b\w/g, l => l.toUpperCase()), value: c }))"
            placeholder="Select category"
          />
          <div>
            <p class="text-sm font-semibold mb-2">Business Logo / Photo</p>
            <input type="file" accept="image/*" class="w-full text-sm" @change="handleLogoUpload" />
            <p v-if="uploading" class="text-xs text-emerald-500 mt-1">Uploading...</p>
            <img v-if="newProvider.image" :src="newProvider.image" class="mt-2 w-24 h-24 object-cover rounded-xl" />
          </div>
          <div>
            <p class="text-sm font-semibold mb-2">Gallery / Work Samples</p>
            <input type="file" accept="image/*" multiple class="w-full text-sm" @change="handleGalleryUpload" />
            <div v-if="newProvider.gallery.length" class="flex gap-2 mt-2 flex-wrap">
              <img v-for="(url, i) in newProvider.gallery" :key="i" :src="url" class="w-16 h-16 object-cover rounded-lg" />
            </div>
          </div>
          <UButton type="submit" color="primary" size="lg" block :loading="uploading">Add Provider</UButton>
        </form>
      </div>
    </div>
  </div>
</template>
