// app/contact/page.tsx
"use client";

import { useState } from "react";
import { motion } from "framer-motion";
import { Send, CheckCircle, Phone, MapPin } from "lucide-react";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

export default function ContactPage() {
  const [form, setForm] = useState({ name: "", email: "", message: "" });
  const [sent, setSent] = useState(false);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    // Send to WhatsApp as fallback
    const text = `Name: ${form.name}\nEmail: ${form.email}\nMessage: ${form.message}`;
    window.open(`https://wa.me/2349115146303?text=${encodeURIComponent(text)}`, "_blank");
    setSent(true);
  };

  return (
    <>
      <Navbar />
      <div className="min-h-screen bg-gray-50 dark:bg-gray-900 py-16 px-4">
        <div className="max-w-2xl mx-auto">
          <h1 className="text-3xl font-bold text-gray-900 dark:text-white mb-2">Contact Us</h1>
          <p className="text-gray-500 dark:text-gray-400 mb-8">Have a question? Send us a message.</p>

          {sent ? (
            <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="text-center py-12">
              <CheckCircle className="w-16 h-16 text-emerald-500 mx-auto mb-4" />
              <h2 className="text-2xl font-bold mb-2">Message Sent!</h2>
              <p className="text-gray-500">We'll get back to you soon.</p>
            </motion.div>
          ) : (
            <form onSubmit={handleSubmit} className="bg-white dark:bg-gray-800 rounded-2xl p-6 shadow-sm space-y-4">
              <input type="text" required placeholder="Your name" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} className="w-full px-4 py-3 border-2 rounded-xl focus:border-emerald-500 focus:outline-none dark:bg-gray-700 dark:border-gray-600 dark:text-white" />
              <input type="email" required placeholder="Your email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} className="w-full px-4 py-3 border-2 rounded-xl focus:border-emerald-500 focus:outline-none dark:bg-gray-700 dark:border-gray-600 dark:text-white" />
              <textarea required placeholder="Your message" rows={5} value={form.message} onChange={(e) => setForm({ ...form, message: e.target.value })} className="w-full px-4 py-3 border-2 rounded-xl focus:border-emerald-500 focus:outline-none dark:bg-gray-700 dark:border-gray-600 dark:text-white" />
              <button type="submit" className="w-full py-3 bg-emerald-500 text-white rounded-xl font-bold hover:bg-emerald-600 flex items-center justify-center gap-2">
                <Send className="w-5 h-5" /> Send Message
              </button>
            </form>
          )}

          <div className="mt-8 grid md:grid-cols-2 gap-4">
            <div className="flex items-center gap-3 bg-white dark:bg-gray-800 p-4 rounded-xl">
              <Phone className="w-5 h-5 text-emerald-500" />
              <span className="text-gray-700 dark:text-gray-300">+234 911 514 6303</span>
            </div>
            <div className="flex items-center gap-3 bg-white dark:bg-gray-800 p-4 rounded-xl">
              <MapPin className="w-5 h-5 text-emerald-500" />
              <span className="text-gray-700 dark:text-gray-300">Jos, Plateau State, Nigeria</span>
            </div>
          </div>
        </div>
      </div>
      <Footer />
    </>
  );
}

// app/pages/contact.vue
<script setup lang="ts">
const form = reactive({ name: '', email: '', message: '' })
const sent = ref(false)

const handleSubmit = () => {
  const text = `Name: ${form.name}\nEmail: ${form.email}\nMessage: ${form.message}`
  window.open(`https://wa.me/2349043832380?text=${encodeURIComponent(text)}`, '_blank')
  sent.value = true
}
</script>

<template>
  <div class="min-h-screen bg-gray-50 dark:bg-gray-900 py-16 px-4">
    <div class="max-w-2xl mx-auto">
      <h1 class="text-3xl font-bold text-gray-900 dark:text-white mb-2">Contact Us</h1>
      <p class="text-gray-500 dark:text-gray-400 mb-8">Have a question? Send us a message.</p>

      <div v-if="sent" class="text-center py-12">
        <div class="text-6xl mb-4">✅</div>
        <h2 class="text-2xl font-bold mb-2 text-gray-900 dark:text-white">Message Sent!</h2>
        <p class="text-gray-500">We'll get back to you soon.</p>
        <UButton class="mt-6" color="primary" @click="sent = false">Send Another</UButton>
      </div>

      <form v-else class="bg-white dark:bg-gray-800 rounded-2xl p-6 shadow-sm space-y-4" @submit.prevent="handleSubmit">
        <UInput v-model="form.name" required placeholder="Your name" size="lg" />
        <UInput v-model="form.email" type="email" required placeholder="Your email" size="lg" />
        <UTextarea v-model="form.message" required placeholder="Your message" :rows="5" size="lg" />
        <UButton type="submit" color="primary" size="lg" block icon="i-lucide-send">Send Message via WhatsApp</UButton>
      </form>

      <div class="mt-8 grid md:grid-cols-2 gap-4">
        <div class="flex items-center gap-3 bg-white dark:bg-gray-800 p-4 rounded-xl shadow-sm">
          <UIcon name="i-lucide-phone" class="w-5 h-5 text-emerald-500" />
          <span class="text-gray-700 dark:text-gray-300">+234 904 383 2380</span>
        </div>
        <div class="flex items-center gap-3 bg-white dark:bg-gray-800 p-4 rounded-xl shadow-sm">
          <UIcon name="i-lucide-map-pin" class="w-5 h-5 text-emerald-500" />
          <span class="text-gray-700 dark:text-gray-300">Jos, Plateau State, Nigeria</span>
        </div>
        <div class="flex items-center gap-3 bg-white dark:bg-gray-800 p-4 rounded-xl shadow-sm">
          <UIcon name="i-lucide-mail" class="w-5 h-5 text-emerald-500" />
          <span class="text-gray-700 dark:text-gray-300">support@josmkt.com.ng</span>
        </div>
        <a href="https://wa.me/2349043832380" target="_blank" class="flex items-center gap-3 bg-green-50 dark:bg-green-900/20 p-4 rounded-xl shadow-sm hover:bg-green-100 dark:hover:bg-green-900/30 transition">
          <UIcon name="i-lucide-message-circle" class="w-5 h-5 text-green-500" />
          <span class="text-green-700 dark:text-green-400 font-medium">Chat on WhatsApp</span>
        </a>
      </div>
    </div>
  </div>
</template>
