// app/dashboard/page.tsx
"use client";

import { motion } from "framer-motion";
import { Heart, MessageCircle, Package, Settings, User } from "lucide-react";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { useAuth } from "@/contexts/AuthContext";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { api } from "@/lib/api";
import { useLanguage } from "@/contexts/LanguageContext";

export default function DashboardPage() {
  const { user } = useAuth();
  const router = useRouter();
  const [orders, setOrders] = useState<any[]>([]);
  const [favorites, setFavorites] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const { t } = useLanguage();

  useEffect(() => {
    if (!user) {
      router.push("/");
      return;
    }

    Promise.all([
      api.getMyOrders(),
      api.getFavorites()
    ]).then(([ordersData, favoritesData]) => {
      setOrders(ordersData);
      setFavorites(favoritesData);
      setLoading(false);
    }).catch(() => setLoading(false));
  }, [user, router]);

  if (!user) return null;

  const stats = [
    { icon: Package, label: t('orders'), value: orders.length.toString(), color: "from-blue-500 to-blue-600" },
    { icon: Heart, label: t('wishlist'), value: favorites.length.toString(), color: "from-pink-500 to-pink-600" },
    { icon: MessageCircle, label: t('messages'), value: "0", color: "from-green-500 to-green-600" },
  ];

  return (
    <>
      <Navbar />
      <div className="min-h-screen bg-gray-50 dark:bg-gray-900 py-8 px-4">
        <div className="max-w-7xl mx-auto">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="mb-8"
          >
            <h1 className="text-4xl font-bold mb-2">{t('welcomeBack')}, {user.name}!</h1>
            <p className="text-gray-600 dark:text-gray-400">{t('manageAccount')}</p>
          </motion.div>

          <div className="grid md:grid-cols-3 gap-6 mb-8">
            {stats.map((stat, i) => {
              const Icon = stat.icon;
              return (
                <motion.div
                  key={i}
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: i * 0.1 }}
                  className="bg-white dark:bg-gray-800 rounded-2xl p-6 shadow-lg"
                >
                  <div className={`w-12 h-12 bg-gradient-to-br ${stat.color} rounded-lg flex items-center justify-center mb-4`}>
                    <Icon className="w-6 h-6 text-white" />
                  </div>
                  <p className="text-3xl font-bold mb-1">{stat.value}</p>
                  <p className="text-gray-600 dark:text-gray-400">{stat.label}</p>
                </motion.div>
              );
            })}
          </div>

          <div className="grid md:grid-cols-2 gap-6">
            <motion.div
              initial={{ opacity: 0, x: -20 }}
              animate={{ opacity: 1, x: 0 }}
              className="bg-white dark:bg-gray-800 rounded-2xl p-6 shadow-lg"
            >
              <h2 className="text-2xl font-bold mb-4">{t('recentOrders')}</h2>
              {loading ? (
                <p>Loading...</p>
              ) : orders.length === 0 ? (
                <p className="text-gray-600">{t('noOrders')}</p>
              ) : (
                <div className="space-y-4">
                  {orders.slice(0, 3).map((order: any) => (
                    <div key={order._id} className="flex items-center gap-4 p-4 border dark:border-gray-700 rounded-lg">
                      <div className="text-4xl">📦</div>
                      <div className="flex-1">
                        <p className="font-semibold">{order.product?.title}</p>
                        <p className="text-sm text-gray-600 dark:text-gray-400">{order.status}</p>
                      </div>
                      <p className="font-bold">₦{order.product?.price.toLocaleString()}</p>
                    </div>
                  ))}
                </div>
              )}
            </motion.div>

            <motion.div
              initial={{ opacity: 0, x: 20 }}
              animate={{ opacity: 1, x: 0 }}
              className="bg-white dark:bg-gray-800 rounded-2xl p-6 shadow-lg"
            >
              <h2 className="text-2xl font-bold mb-4">{t('quickActions')}</h2>
              <div className="space-y-3">
                <button onClick={() => router.push('/wishlist')} className="w-full text-left p-4 border dark:border-gray-700 rounded-lg hover:bg-gray-50 dark:hover:bg-gray-700 flex items-center gap-3">
                  <Heart className="w-5 h-5" />
                  <span>{t('viewWishlist')}</span>
                </button>
                {user.role === 'seller' && (
                  <button onClick={() => router.push('/upload-product')} className="w-full text-left p-4 border dark:border-gray-700 rounded-lg hover:bg-gray-50 dark:hover:bg-gray-700 flex items-center gap-3">
                    <Package className="w-5 h-5" />
                    <span>{t('uploadProduct')}</span>
                  </button>
                )}
                <button className="w-full text-left p-4 border dark:border-gray-700 rounded-lg hover:bg-gray-50 dark:hover:bg-gray-700 flex items-center gap-3">
                  <Settings className="w-5 h-5" />
                  <span>{t('settings')}</span>
                </button>
              </div>
            </motion.div>
          </div>
        </div>
      </div>
      <Footer />
    </>
  );
}

// app/pages/dashboard.vue
<script setup lang="ts">
definePageMeta({ middleware: 'auth' })
const user = useSupabaseUser()
const supabase = useSupabaseClient()
const orders = ref<any[]>([])
const favorites = ref<any[]>([])
const loading = ref(true)

onMounted(async () => {
  const [{ data: o }, { data: f }] = await Promise.all([
    supabase.from('orders').select('*, product:products(*)').eq('buyer_id', user.value?.id).order('created_at', { ascending: false }).limit(5),
    supabase.from('favorites').select('*, product:products(*)').eq('user_id', user.value?.id).limit(5)
  ])
  orders.value = o || []
  favorites.value = f || []
  loading.value = false
})

const stats = computed(() => [
  { label: 'Orders', value: orders.value.length, icon: 'i-lucide-package', color: 'bg-blue-500' },
  { label: 'Wishlist', value: favorites.value.length, icon: 'i-lucide-heart', color: 'bg-pink-500' },
  { label: 'Messages', value: 0, icon: 'i-lucide-message-circle', color: 'bg-green-500' },
])
</script>

<template>
  <div class="min-h-screen bg-gray-50 dark:bg-gray-900 py-8 px-4">
    <div class="max-w-7xl mx-auto">
      <div class="mb-8 animate-fade-up">
        <h1 class="text-3xl font-black text-gray-900 dark:text-white mb-1">Welcome back! 👋</h1>
        <p class="text-gray-600 dark:text-gray-400">{{ user?.email }}</p>
      </div>

      <div class="grid grid-cols-3 gap-4 md:gap-6 mb-8">
        <div v-for="stat in stats" :key="stat.label" class="bg-white dark:bg-gray-800 rounded-2xl p-4 md:p-6 shadow-md card-hover animate-fade-up">
          <div class="w-10 h-10 md:w-12 md:h-12 rounded-xl flex items-center justify-center mb-3 md:mb-4" :class="stat.color">
            <UIcon :name="stat.icon" class="w-5 h-5 md:w-6 md:h-6 text-white" />
          </div>
          <p class="text-2xl md:text-3xl font-black mb-1">{{ stat.value }}</p>
          <p class="text-xs md:text-sm text-gray-600 dark:text-gray-400">{{ stat.label }}</p>
        </div>
      </div>

      <div class="grid md:grid-cols-2 gap-6">
        <div class="bg-white dark:bg-gray-800 rounded-2xl p-6 shadow-md">
          <h2 class="text-xl font-black mb-4">Recent Orders</h2>
          <div v-if="loading" class="space-y-3">
            <div v-for="i in 3" :key="i" class="skeleton h-16 rounded-xl" />
          </div>
          <div v-else-if="orders.length === 0" class="text-center py-8 text-gray-500">No orders yet</div>
          <div v-else class="space-y-3">
            <div v-for="order in orders" :key="order.id" class="flex items-center gap-3 p-3 border dark:border-gray-700 rounded-xl">
              <div class="text-3xl">📦</div>
              <div class="flex-1 min-w-0">
                <p class="font-semibold truncate">{{ order.product?.title }}</p>
                <UBadge :color="order.status === 'completed' ? 'success' : order.status === 'cancelled' ? 'error' : 'warning'" size="xs">{{ order.status }}</UBadge>
              </div>
              <p class="font-bold text-primary-600">₦{{ order.product?.price?.toLocaleString() }}</p>
            </div>
          </div>
        </div>

        <div class="bg-white dark:bg-gray-800 rounded-2xl p-6 shadow-md">
          <h2 class="text-xl font-black mb-4">Quick Actions</h2>
          <div class="space-y-3">
            <UButton to="/wishlist" variant="outline" color="neutral" block icon="i-lucide-heart" class="justify-start">View Wishlist</UButton>
            <UButton to="/orders" variant="outline" color="neutral" block icon="i-lucide-package" class="justify-start">All Orders</UButton>
            <UButton to="/upload-product" variant="outline" color="neutral" block icon="i-lucide-plus" class="justify-start">Upload Product</UButton>
            <UButton to="/seller-dashboard" variant="outline" color="neutral" block icon="i-lucide-store" class="justify-start">Seller Dashboard</UButton>
            <UButton to="/profile" variant="outline" color="neutral" block icon="i-lucide-settings" class="justify-start">Edit Profile</UButton>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>
