// app/forgot-password/page.tsx
"use client";

import { useState } from "react";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Mail } from "lucide-react";

export default function ForgotPasswordPage() {
  const [email, setEmail] = useState("");
  const [loading, setLoading] = useState(false);
  const [sent, setSent] = useState(false);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);

    try {
      const response = await fetch('http://localhost:5000/api/auth/forgot-password', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ email })
      });

      if (response.ok) {
        setSent(true);
      } else {
        alert('Email not found');
      }
    } catch (error) {
      alert('Failed to send reset email');
    }
    setLoading(false);
  };

  return (
    <>
      <Navbar />
      <div className="min-h-screen bg-gray-50 flex items-center justify-center px-4">
        <div className="max-w-md w-full bg-white rounded-2xl p-8 shadow-lg">
          {sent ? (
            <div className="text-center">
              <div className="w-16 h-16 bg-green-100 rounded-full flex items-center justify-center mx-auto mb-4">
                <Mail className="w-8 h-8 text-green-600" />
              </div>
              <h2 className="text-2xl font-bold mb-2">Check Your Email</h2>
              <p className="text-gray-600 mb-6">
                We've sent a password reset link to <strong>{email}</strong>
              </p>
              <button
                onClick={() => window.location.href = '/'}
                className="px-6 py-2 bg-primary-500 text-white rounded-lg font-semibold hover:bg-primary-600"
              >
                Back to Home
              </button>
            </div>
          ) : (
            <>
              <h1 className="text-3xl font-bold mb-2">Forgot Password?</h1>
              <p className="text-gray-600 mb-6">Enter your email to receive a reset link</p>

              <form onSubmit={handleSubmit} className="space-y-4">
                <div>
                  <label className="block font-semibold mb-2">Email</label>
                  <input
                    type="email"
                    required
                    value={email}
                    onChange={(e) => setEmail(e.target.value)}
                    placeholder="your@email.com"
                    className="w-full px-4 py-3 border rounded-lg focus:border-primary-500 focus:outline-none"
                  />
                </div>

                <button
                  type="submit"
                  disabled={loading}
                  className="w-full py-3 bg-primary-500 text-white rounded-lg font-bold hover:bg-primary-600 disabled:opacity-50"
                >
                  {loading ? 'Sending...' : 'Send Reset Link'}
                </button>

                <button
                  type="button"
                  onClick={() => window.location.href = '/'}
                  className="w-full py-3 border rounded-lg font-semibold hover:bg-gray-50"
                >
                  Cancel
                </button>
              </form>
            </>
          )}
        </div>
      </div>
      <Footer />
    </>
  );
}

// app/pages/forgot-password.vue
<script setup lang="ts">
definePageMeta({ layout: 'default' })
const supabase = useSupabaseClient()
const toast = useToast()
const email = ref('')
const loading = ref(false)
const sent = ref(false)

const submit = async () => {
  loading.value = true
  const { error } = await supabase.auth.resetPasswordForEmail(email.value, {
    redirectTo: `${window.location.origin}/reset-password`
  })
  if (error) {
    toast.add({ title: error.message, color: 'error' })
  } else {
    sent.value = true
  }
  loading.value = false
}
</script>

<template>
  <div class="min-h-screen flex items-center justify-center px-4">
    <div class="w-full max-w-md">
      <UCard class="shadow-xl p-2">
        <div v-if="sent" class="text-center py-4">
          <div class="text-5xl mb-4">📧</div>
          <h2 class="text-2xl font-black mb-2">Check Your Email</h2>
          <p class="text-gray-500 mb-6">We sent a password reset link to <strong>{{ email }}</strong></p>
          <UButton to="/login" color="primary" block>Back to Login</UButton>
        </div>
        <div v-else>
          <div class="text-center mb-6">
            <h1 class="text-2xl font-black text-gray-900 dark:text-white">Forgot Password</h1>
            <p class="text-gray-500 text-sm mt-1">Enter your email to reset your password</p>
          </div>
          <form class="space-y-4" @submit.prevent="submit">
            <UFormField label="Email">
              <UInput v-model="email" type="email" placeholder="your@email.com" icon="i-lucide-mail" size="lg" class="w-full" required />
            </UFormField>
            <UButton type="submit" color="primary" size="lg" block :loading="loading">Send Reset Link</UButton>
            <div class="text-center">
              <NuxtLink to="/login" class="text-sm text-emerald-600 hover:underline">Back to Login</NuxtLink>
            </div>
          </form>
        </div>
      </UCard>
    </div>
  </div>
</template>
