// app/trending/page.tsx
'use client';

import { useEffect, useState } from 'react';
import { api } from '@/lib/api';
import { TrendingUp, Heart, Eye } from 'lucide-react';

export default function Trending() {
  const [products, setProducts] = useState<any[]>([]);
  const [period, setPeriod] = useState('7d');

  useEffect(() => {
    loadTrending();
  }, [period]);

  const loadTrending = async () => {
    const data = await api.getTrending(period);
    setProducts(data);
  };

  return (
    <div className="min-h-screen bg-gray-50 pt-20 pb-12">
      <div className="max-w-7xl mx-auto px-4">
        <div className="flex flex-col md:flex-row items-start md:items-center justify-between mb-8 gap-4">
          <div className="flex items-center gap-3">
            <TrendingUp className="w-6 h-6 md:w-8 md:h-8 text-primary-500" />
            <h1 className="text-2xl md:text-3xl font-bold">Trending Products</h1>
          </div>
          <div className="flex gap-2">
            <button
              onClick={() => setPeriod('24h')}
              className={`px-3 md:px-4 py-2 rounded-lg text-sm md:text-base ${period === '24h' ? 'bg-primary-500 text-white' : 'bg-white'}`}
            >
              24 Hours
            </button>
            <button
              onClick={() => setPeriod('7d')}
              className={`px-3 md:px-4 py-2 rounded-lg text-sm md:text-base ${period === '7d' ? 'bg-primary-500 text-white' : 'bg-white'}`}
            >
              7 Days
            </button>
          </div>
        </div>

        <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4 md:gap-6">
          {products.map((product, index) => (
            <div key={product._id} className="bg-white rounded-lg shadow overflow-hidden">
              <div className="relative">
                <img src={product.images[0]} alt={product.title} className="w-full h-40 md:h-48 object-cover" />
                <div className="absolute top-2 left-2 bg-primary-500 text-white px-3 py-1 rounded-full text-sm font-bold">
                  #{index + 1}
                </div>
              </div>
              <div className="p-3 md:p-4">
                <h3 className="font-semibold text-sm md:text-base mb-2 line-clamp-2">{product.title}</h3>
                <p className="text-lg md:text-2xl font-bold text-primary-500 mb-3">₦{product.price.toLocaleString()}</p>
                <div className="flex items-center justify-between text-sm text-gray-600 mb-3">
                  <div className="flex items-center gap-1">
                    <Eye className="w-4 h-4" />
                    {product.views}
                  </div>
                  <div className="flex items-center gap-1">
                    <Heart className="w-4 h-4" />
                    {product.favorites?.length || 0}
                  </div>
                </div>
                <a
                  href={`/product/${product._id}`}
                  className="block w-full py-2 bg-primary-500 text-white text-center rounded-lg hover:bg-primary-600"
                >
                  View Details
                </a>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

// app/pages/trending.vue
<script setup lang="ts">
const supabase = useSupabaseClient()
const products = ref<any[]>([])
const loading = ref(true)
const period = ref('7d')

const loadTrending = async () => {
  loading.value = true
  const { data } = await supabase
    .from('products')
    .select('*, seller:profiles(*)')
    .eq('status', 'active')
    .order('views', { ascending: false })
    .limit(20)
  products.value = data || []
  loading.value = false
}

watch(period, loadTrending)
onMounted(loadTrending)
</script>

<template>
  <div class="min-h-screen bg-gray-50 dark:bg-gray-900 py-8 px-4">
    <div class="max-w-7xl mx-auto">
      <div class="flex flex-col md:flex-row items-start md:items-center justify-between mb-8 gap-4">
        <div class="flex items-center gap-3">
          <UIcon name="i-lucide-trending-up" class="w-8 h-8 text-emerald-500" />
          <h1 class="text-2xl md:text-3xl font-bold text-gray-900 dark:text-white">Trending Products</h1>
        </div>
        <div class="flex gap-2">
          <UButton :variant="period === '24h' ? 'solid' : 'outline'" :color="period === '24h' ? 'primary' : 'neutral'" size="sm" @click="period = '24h'">24 Hours</UButton>
          <UButton :variant="period === '7d' ? 'solid' : 'outline'" :color="period === '7d' ? 'primary' : 'neutral'" size="sm" @click="period = '7d'">7 Days</UButton>
        </div>
      </div>

      <div v-if="loading" class="grid grid-cols-2 md:grid-cols-4 gap-4">
        <div v-for="i in 8" :key="i" class="rounded-2xl overflow-hidden">
          <div class="skeleton aspect-square" />
          <div class="p-4 space-y-2">
            <div class="skeleton h-4 rounded w-3/4" />
            <div class="skeleton h-4 rounded w-1/2" />
          </div>
        </div>
      </div>

      <div v-else-if="products.length === 0" class="text-center py-20">
        <div class="text-6xl mb-4">📈</div>
        <h3 class="text-xl font-bold text-gray-900 dark:text-white mb-2">No trending products yet</h3>
        <UButton to="/products" color="primary">Browse All Products</UButton>
      </div>

      <div v-else class="grid grid-cols-2 md:grid-cols-4 gap-4 md:gap-6">
        <NuxtLink
          v-for="(product, index) in products"
          :key="product.id"
          :to="`/product/${product.id}`"
          class="bg-white dark:bg-gray-800 rounded-2xl overflow-hidden shadow-md hover:shadow-xl transition-all group"
        >
          <div class="relative">
            <div class="aspect-square bg-gray-100 dark:bg-gray-700 overflow-hidden">
              <img v-if="product.images?.[0]" :src="product.images[0]" :alt="product.title" class="w-full h-full object-cover group-hover:scale-105 transition-transform duration-300" />
              <div v-else class="w-full h-full flex items-center justify-center text-7xl">📦</div>
            </div>
            <div class="absolute top-2 left-2 px-3 py-1 bg-emerald-500 text-white text-sm font-bold rounded-full">
              #{{ index + 1 }}
            </div>
          </div>
          <div class="p-3 md:p-4">
            <h3 class="font-semibold text-sm md:text-base mb-2 line-clamp-2 text-gray-900 dark:text-white">{{ product.title }}</h3>
            <p class="text-lg md:text-2xl font-bold text-emerald-600 mb-2">₦{{ product.price?.toLocaleString() }}</p>
            <div class="flex items-center justify-between text-sm text-gray-500">
              <div class="flex items-center gap-1">
                <UIcon name="i-lucide-eye" class="w-4 h-4" />
                {{ product.views || 0 }}
              </div>
              <div class="flex items-center gap-1">
                <UIcon name="i-lucide-heart" class="w-4 h-4" />
                {{ product.favorites_count || 0 }}
              </div>
            </div>
          </div>
        </NuxtLink>
      </div>
    </div>
  </div>
</template>
