// app/upload-product/page.tsx
"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { Upload, X } from "lucide-react";
import { api } from "@/lib/api";
import { useAuth } from "@/contexts/AuthContext";

export default function UploadProduct() {
  const router = useRouter();
  const { user } = useAuth();
  const [images, setImages] = useState<File[]>([]);
  const [previews, setPreviews] = useState<string[]>([]);
  const [loading, setLoading] = useState(false);
  const [formData, setFormData] = useState({
    title: "",
    description: "",
    price: "",
    category: "Electronics",
    condition: "new",
    location: "Bukuru",
    stock: "1",
    tags: ""
  });

  if (!user) {
    router.push("/");
    return null;
  }

  const handleImageChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const files = Array.from(e.target.files || []) as File[];
    if (images.length + files.length > 8) {
      alert("Maximum 8 images allowed");
      return;
    }
    
    setImages([...images, ...files]);
    files.forEach(file => {
      const reader = new FileReader();
      reader.onloadend = () => setPreviews(prev => [...prev, reader.result as string]);
      reader.readAsDataURL(file);
    });
  };

  const removeImage = (index: number) => {
    setImages(images.filter((_, i) => i !== index));
    setPreviews(previews.filter((_, i) => i !== index));
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);

    try {
      const formDataToSend = new FormData();
      formDataToSend.append("title", formData.title);
      formDataToSend.append("description", formData.description);
      formDataToSend.append("price", formData.price);
      formDataToSend.append("category", formData.category);
      formDataToSend.append("condition", formData.condition);
      formDataToSend.append("location", formData.location);
      formDataToSend.append("stock", formData.stock);
      if (formData.tags) {
        formDataToSend.append("tags", JSON.stringify(formData.tags.split(",").map(t => t.trim())));
      }
      
      images.forEach(image => {
        formDataToSend.append("images", image);
      });

      await api.createProduct(formDataToSend);
      alert("Product uploaded successfully!");
      router.push("/dashboard");
    } catch (error: any) {
      alert(error.message || "Failed to upload product");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-gray-50 py-12 px-4">
      <div className="max-w-3xl mx-auto bg-white rounded-2xl shadow-lg p-8">
        <h1 className="text-3xl font-bold mb-8">Upload Product</h1>

        <form onSubmit={handleSubmit} className="space-y-6">
          <div>
            <label className="block font-semibold mb-2">Product Images (Max 8)</label>
            <div className="grid grid-cols-4 gap-4 mb-4">
              {previews.map((preview, index) => (
                <div key={index} className="relative aspect-square">
                  <img src={preview} alt="" className="w-full h-full object-cover rounded-lg" />
                  <button
                    type="button"
                    onClick={() => removeImage(index)}
                    className="absolute -top-2 -right-2 bg-red-500 text-white rounded-full p-1"
                  >
                    <X className="w-4 h-4" />
                  </button>
                </div>
              ))}
              {images.length < 8 && (
                <label className="aspect-square border-2 border-dashed rounded-lg flex items-center justify-center cursor-pointer hover:border-primary-500">
                  <input type="file" multiple accept="image/*" onChange={handleImageChange} className="hidden" />
                  <Upload className="w-8 h-8 text-gray-400" />
                </label>
              )}
            </div>
          </div>

          <div>
            <label className="block font-semibold mb-2">Title</label>
            <input
              type="text"
              required
              value={formData.title}
              onChange={(e) => setFormData({ ...formData, title: e.target.value })}
              className="w-full px-4 py-3 border rounded-lg focus:border-primary-500 focus:outline-none"
            />
          </div>

          <div>
            <label className="block font-semibold mb-2">Description</label>
            <textarea
              required
              rows={4}
              value={formData.description}
              onChange={(e) => setFormData({ ...formData, description: e.target.value })}
              className="w-full px-4 py-3 border rounded-lg focus:border-primary-500 focus:outline-none"
            />
          </div>

          <div className="grid grid-cols-2 gap-4">
            <div>
              <label className="block font-semibold mb-2">Price (₦)</label>
              <input
                type="number"
                required
                value={formData.price}
                onChange={(e) => setFormData({ ...formData, price: e.target.value })}
                className="w-full px-4 py-3 border rounded-lg focus:border-primary-500 focus:outline-none"
              />
            </div>
            <div>
              <label className="block font-semibold mb-2">Stock</label>
              <input
                type="number"
                required
                value={formData.stock}
                onChange={(e) => setFormData({ ...formData, stock: e.target.value })}
                className="w-full px-4 py-3 border rounded-lg focus:border-primary-500 focus:outline-none"
              />
            </div>
          </div>

          <div className="grid grid-cols-2 gap-4">
            <div>
              <label className="block font-semibold mb-2">Category</label>
              <select
                value={formData.category}
                onChange={(e) => setFormData({ ...formData, category: e.target.value })}
                className="w-full px-4 py-3 border rounded-lg focus:border-primary-500 focus:outline-none"
              >
                <option>Electronics</option>
                <option>Fashion</option>
                <option>Home & Properties</option>
                <option>Sports</option>
                <option>Books</option>
                <option>Food</option>
                <option>Automotive</option>
                <option>Services</option>
              </select>
            </div>
            <div>
              <label className="block font-semibold mb-2">Condition</label>
              <select
                value={formData.condition}
                onChange={(e) => setFormData({ ...formData, condition: e.target.value })}
                className="w-full px-4 py-3 border rounded-lg focus:border-primary-500 focus:outline-none"
              >
                <option value="new">New</option>
                <option value="used">Used</option>
                <option value="refurbished">Refurbished</option>
              </select>
            </div>
          </div>

          <div>
            <label className="block font-semibold mb-2">Location</label>
            <select
              value={formData.location}
              onChange={(e) => setFormData({ ...formData, location: e.target.value })}
              className="w-full px-4 py-3 border rounded-lg focus:border-primary-500 focus:outline-none"
            >
              <option>Bukuru</option>
              <option>Rayfield</option>
              <option>Terminus</option>
              <option>Lamingo</option>
              <option>Angwan Rogo</option>
            </select>
          </div>

          <div>
            <label className="block font-semibold mb-2">Tags (comma separated)</label>
            <input
              type="text"
              value={formData.tags}
              onChange={(e) => setFormData({ ...formData, tags: e.target.value })}
              placeholder="e.g. wireless, bluetooth, headphones"
              className="w-full px-4 py-3 border rounded-lg focus:border-primary-500 focus:outline-none"
            />
          </div>

          <button
            type="submit"
            disabled={loading}
            className="w-full py-4 bg-primary-500 text-white rounded-lg font-bold hover:bg-primary-600 disabled:opacity-50"
          >
            {loading ? "Uploading..." : "Upload Product"}
          </button>
        </form>
      </div>
    </div>
  );
}

// app/pages/upload-product.vue
<script setup lang="ts">
definePageMeta({ layout: 'default' })
const user = useSupabaseUser()
const supabase = useSupabaseClient()
const toast = useToast()
const router = useRouter()
const loading = ref(false)
const previews = ref<string[]>([])
const files = ref<File[]>([])

const form = reactive({
  title: '', description: '', price: '', category: 'Electronics',
  condition: 'new', location: 'Bukuru', stock: '1', tags: ''
})

const categories = ['Electronics', 'Fashion', 'Food', 'Home', 'Sports', 'Automotive', 'Books', 'Services']
const locations = ['Bukuru', 'Rayfield', 'Terminus', 'Lamingo', 'Angwan Rogo', 'Tudun Wada', 'Zaria Road']

const handleImages = (e: Event) => {
  const input = e.target as HTMLInputElement
  const selected = Array.from(input.files || [])
  if (files.value.length + selected.length > 8) return toast.add({ title: 'Max 8 images', color: 'error' })
  files.value = [...files.value, ...selected]
  selected.forEach(f => {
    const reader = new FileReader()
    reader.onloadend = () => previews.value.push(reader.result as string)
    reader.readAsDataURL(f)
  })
}

const removeImage = (i: number) => {
  files.value.splice(i, 1)
  previews.value.splice(i, 1)
}

const submit = async () => {
  if (!form.title || !form.price) return toast.add({ title: 'Fill all required fields', color: 'error' })
  loading.value = true
  try {
    const imageUrls: string[] = []
    for (const file of files.value) {
      const ext = file.name.split('.').pop()
      const path = `products/${user.value?.id}/${Date.now()}.${ext}`
      const { error } = await supabase.storage.from('images').upload(path, file)
      if (!error) {
        const { data } = supabase.storage.from('images').getPublicUrl(path)
        imageUrls.push(data.publicUrl)
      }
    }
    const { error } = await supabase.from('products').insert({
      title: form.title, description: form.description, price: Number(form.price),
      category: form.category, condition: form.condition, location: form.location,
      stock: Number(form.stock), images: imageUrls, seller_id: user.value?.id, status: 'active',
      tags: form.tags ? form.tags.split(',').map(t => t.trim()) : []
    })
    if (error) throw error
    toast.add({ title: 'Product uploaded!', color: 'success' })
    router.push('/dashboard')
  } catch (e: any) {
    toast.add({ title: e.message, color: 'error' })
  }
  loading.value = false
}
</script>

<template>
  <div class="min-h-screen bg-gray-50 dark:bg-gray-900 py-8 px-4">
    <div class="max-w-3xl mx-auto">
      <h1 class="text-3xl font-black mb-8 text-gray-900 dark:text-white">Upload Product</h1>

      <UCard class="shadow-lg">
        <form class="space-y-6" @submit.prevent="submit">
          <!-- Images -->
          <div>
            <label class="block font-semibold mb-3">Product Images (Max 8)</label>
            <div class="grid grid-cols-4 gap-3 mb-3">
              <div v-for="(preview, i) in previews" :key="i" class="relative aspect-square">
                <img :src="preview" class="w-full h-full object-cover rounded-xl" />
                <UButton icon="i-lucide-x" color="error" size="xs" class="absolute -top-2 -right-2 rounded-full" @click="removeImage(i)" />
              </div>
              <label v-if="files.length < 8" class="aspect-square border-2 border-dashed border-gray-300 rounded-xl flex items-center justify-center cursor-pointer hover:border-primary-500 transition-colors">
                <input type="file" multiple accept="image/*" class="hidden" @change="handleImages" />
                <UIcon name="i-lucide-upload" class="w-8 h-8 text-gray-400" />
              </label>
            </div>
          </div>

          <UFormField label="Title *">
            <UInput v-model="form.title" placeholder="Product title" size="lg" class="w-full" required />
          </UFormField>

          <UFormField label="Description *">
            <UTextarea v-model="form.description" placeholder="Describe your product..." :rows="4" class="w-full" required />
          </UFormField>

          <div class="grid grid-cols-2 gap-4">
            <UFormField label="Price (₦) *">
              <UInput v-model="form.price" type="number" placeholder="0" size="lg" class="w-full" required />
            </UFormField>
            <UFormField label="Stock">
              <UInput v-model="form.stock" type="number" placeholder="1" size="lg" class="w-full" />
            </UFormField>
          </div>

          <div class="grid grid-cols-2 gap-4">
            <UFormField label="Category">
              <USelect v-model="form.category" :items="categories" size="lg" class="w-full" />
            </UFormField>
            <UFormField label="Condition">
              <USelect v-model="form.condition" :items="['new','used','refurbished']" size="lg" class="w-full" />
            </UFormField>
          </div>

          <UFormField label="Location">
            <USelect v-model="form.location" :items="locations" size="lg" class="w-full" />
          </UFormField>

          <UFormField label="Tags (comma separated)">
            <UInput v-model="form.tags" placeholder="e.g. wireless, bluetooth" size="lg" class="w-full" />
          </UFormField>

          <UButton type="submit" color="primary" size="xl" block :loading="loading">
            Upload Product
          </UButton>
        </form>
      </UCard>
    </div>
  </div>
</template>
