// app/pages/orders.vue
<script setup lang="ts">
definePageMeta({ middleware: 'auth' })
const user = useSupabaseUser()
const supabase = useSupabaseClient()
const orders = ref<any[]>([])
const loading = ref(true)

onMounted(async () => {
  const { data } = await supabase.from('orders').select('*, product:products(*), seller:profiles(*)').eq('buyer_id', user.value?.id).order('created_at', { ascending: false })
  orders.value = data || []
  loading.value = false
})
</script>

<template>
  <div class="min-h-screen bg-gray-50 dark:bg-gray-900 py-8 px-4">
    <div class="max-w-7xl mx-auto">
      <h1 class="text-3xl font-black mb-8 text-gray-900 dark:text-white">Order History</h1>
      <div v-if="loading" class="space-y-4">
        <div v-for="i in 3" :key="i" class="skeleton h-28 rounded-2xl" />
      </div>
      <div v-else-if="orders.length === 0" class="text-center py-20">
        <div class="text-6xl mb-4">📦</div>
        <h3 class="text-xl font-bold mb-2">No orders yet</h3>
        <UButton to="/products" color="primary">Start Shopping</UButton>
      </div>
      <div v-else class="space-y-4">
        <div v-for="order in orders" :key="order.id" class="bg-white dark:bg-gray-800 rounded-2xl p-6 shadow-md flex items-start gap-4">
          <div class="w-20 h-20 bg-gray-100 rounded-xl overflow-hidden flex-shrink-0">
            <img v-if="order.product?.images?.[0]" :src="order.product.images[0]" :alt="order.product.title" class="w-full h-full object-cover" />
            <div v-else class="w-full h-full flex items-center justify-center text-3xl">📦</div>
          </div>
          <div class="flex-1">
            <h3 class="font-bold text-lg mb-1">{{ order.product?.title }}</h3>
            <p class="text-gray-600 text-sm mb-2">Seller: {{ order.seller?.shop_name || order.seller?.full_name }}</p>
            <div class="flex items-center gap-3">
              <span class="text-xl font-black text-primary-600">₦{{ order.product?.price?.toLocaleString() }}</span>
              <UBadge :color="order.status === 'completed' ? 'success' : order.status === 'cancelled' ? 'error' : 'warning'">{{ order.status }}</UBadge>
            </div>
            <p class="text-xs text-gray-400 mt-1">{{ new Date(order.created_at).toLocaleDateString() }}</p>
          </div>
          <UButton icon="i-lucide-message-circle" color="success" size="sm" @click="() => window.open(`https://wa.me/${order.seller?.phone}`, '_blank')" />
        </div>
      </div>
    </div>
  </div>
</template>

// app/orders/page.tsx
"use client";

import { useState, useEffect } from "react";
import { useRouter } from "next/navigation";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { useAuth } from "@/contexts/AuthContext";
import { api } from "@/lib/api";
import { Package, MessageCircle } from "lucide-react";

export default function OrdersPage() {
  const { user } = useAuth();
  const router = useRouter();
  const [orders, setOrders] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (!user) {
      router.push("/");
      return;
    }
    
    api.getMyOrders().then(data => {
      setOrders(Array.isArray(data) ? data : []);
      setLoading(false);
    }).catch(() => setLoading(false));
  }, [user, router]);

  if (!user) return null;

  return (
    <>
      <Navbar />
      <div className="min-h-screen bg-gray-50 py-8 px-4">
        <div className="max-w-7xl mx-auto">
          <h1 className="text-4xl font-bold mb-8">Order History</h1>

          {loading ? (
            <p>Loading...</p>
          ) : orders.length === 0 ? (
            <div className="bg-white rounded-2xl p-12 text-center shadow-lg">
              <Package className="w-16 h-16 text-gray-400 mx-auto mb-4" />
              <h3 className="text-xl font-semibold mb-2">No Orders Yet</h3>
              <p className="text-gray-600 mb-6">Start shopping to see your orders here</p>
              <button
                onClick={() => router.push('/products')}
                className="px-6 py-3 bg-primary-500 text-white rounded-lg font-semibold hover:bg-primary-600"
              >
                Browse Products
              </button>
            </div>
          ) : (
            <div className="space-y-4">
              {orders.map((order: any) => (
                <div key={order._id} className="bg-white rounded-2xl p-6 shadow-lg">
                  <div className="flex items-start gap-4">
                    <div className="w-20 h-20 bg-gray-100 rounded-lg overflow-hidden">
                      {order.product?.images?.[0] ? (
                        <img src={order.product.images[0]} alt={order.product.title} className="w-full h-full object-cover" />
                      ) : (
                        <div className="w-full h-full flex items-center justify-center text-3xl">📦</div>
                      )}
                    </div>
                    <div className="flex-1">
                      <h3 className="font-bold text-lg mb-1">{order.product?.title}</h3>
                      <p className="text-gray-600 mb-2">Seller: {order.seller?.shopName || order.seller?.name}</p>
                      <div className="flex items-center gap-4">
                        <span className="text-2xl font-bold text-primary-600">₦{order.product?.price.toLocaleString()}</span>
                        <span className={`px-3 py-1 rounded-full text-sm font-semibold ${
                          order.status === 'completed' ? 'bg-green-100 text-green-600' :
                          order.status === 'cancelled' ? 'bg-red-100 text-red-600' :
                          'bg-yellow-100 text-yellow-600'
                        }`}>
                          {order.status}
                        </span>
                      </div>
                      <p className="text-sm text-gray-500 mt-2">{new Date(order.createdAt).toLocaleDateString()}</p>
                    </div>
                    <button
                      onClick={() => window.open(`https://wa.me/${order.seller?.phone}`, '_blank')}
                      className="px-4 py-2 bg-primary-500 text-white rounded-lg hover:bg-primary-600 flex items-center gap-2"
                    >
                      <MessageCircle className="w-5 h-5" />
                      Contact
                    </button>
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>
      </div>
      <Footer />
    </>
  );
}
